title               : "Sunni Manhaj"
description         : ""
baseurl             : "/"
keywords            : ""
url                 : "https://sunnimanhaj.github.io"
github_username     : sunnimanhaj
permalink           : pretty
markdown            : kramdown
paginate            : 10
paginate_path       : "/:num/"

include:
  - _pages

compress_html:
  clippings: false

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

exclude:
  - bin
  - config
  - vite.config.ts
  - tmp
  - Procfile.dev
  - docs/
  - vendor/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Makefile
  - README.md
  - sample*.png
  - .gitignore
  - README
  - gemfile
  - Gemfile.lock
  - node_modules
  - jekyll-cache
  - LICENSE
  - CODE_OF-CONDUCT

defaults:
  - scope:
      path: "_posts/**"
      type: posts
    values:
      layout: post
      permalink: /:title/
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: page

